{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memex.fullname" . }}-auth
  labels: {{- include "memex.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
